Add findJavaHomePromise to export
jsdevel/node-find-java-home pull request #30
Opened 2021-03-02 02:44 UTC by Coder-Iro

2021-03-02 16:56 UTC, jsdevel requested changes

2021-03-02 16:56 UTC, jsdevel commented on test.js
> +  var sut = require('./').findJavaHome;
yea, we're not going to change the export interface for this.  can you assign findJavaHomePromise as a property to findJavaHome?  That way you can do `require('find-java-home').findJavaHomePromise`.  Or maybe this is better? `require('find-java-home').promise`

2021-03-04 02:28 UTC, Coder-Iro commented
Travis check is failing because node 8 is too low

2021-03-09 07:19 UTC, Coder-Iro commented
@jsdevel PLZ merge this PR ASAP. I have to use this module in my project.

2021-03-11 00:07 UTC, Coder-Iro commented on package.json
> -    "mocha": "~1.18.2",
I reverted that change.

2021-04-08 03:48 UTC, jsdevel requested changes
sorry for the late re-review.  can you completely remove package-lock.json changes?

2021-04-08 03:56 UTC, merged

2021-04-08 04:00 UTC, Coder-Iro commented
When will this change be distributed to the npm registry?

2021-05-14 16:32 UTC, jsdevel commented
@Coder-Iro it should be in 1.2.0

2021-05-15 12:10 UTC, Coder-Iro commented
I think there should be another example for Promise in README.

2021-05-25 16:53 UTC, jsdevel commented
@Coder-Iro please submit a pr!